version: "3.8"

services:
  mongodb:
    image: mongo:5.0
    container_name: ${COMPOSE_PROJECT_NAME}_mongodb
    ports:
      - "27017:27017"
    volumes:
      - .mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=app
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
