service: serverless-app

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  health:
    handler: dist/core/infrastructure/http/handlers/health.handler
    events:
      - httpApi:
          path: /health
          method: get
  info:
    handler: dist/core/infrastructure/http/handlers/info.handler
    events:
      - httpApi:
          path: /info
          method: get
  listCustomers:
    handler: dist/customers/infrastructure/http/handlers/list-customers.handler
    events:
      - httpApi:
          path: /customers
          method: get
  getCustomer:
    handler: dist/customers/infrastructure/http/handlers/get-customer.handler
    events:
      - httpApi:
          path: /customers/{id}
          method: get
  createCustomer:
    handler: dist/customers/infrastructure/http/handlers/create-customer.handler
    events:
      - httpApi:
          path: /customers
          method: post
  updateCustomer:
    handler: dist/customers/infrastructure/http/handlers/update-customer.handler
    events:
      - httpApi:
          path: /customers/{id}
          method: patch
  deleteCustomer:
    handler: dist/customers/infrastructure/http/handlers/delete-customer.handler
    events:
      - httpApi:
          path: /customers/{id}
          method: delete
  createCustomerCredits:
    handler: dist/customers/infrastructure/http/handlers/get-customer-credits.handler
    events:
      - httpApi:
          path: /customers/{customerId}/credits
          method: get
  getCustomerCredit:
    handler: dist/customers/infrastructure/http/handlers/get-customer-credit.handler
    events:
      - httpApi:
          path: /customers/{customerId}/credits/{creditId}
          method: get
  createCustomerCredit:
    handler: dist/customers/infrastructure/http/handlers/create-customer-credit.handler
    events:
      - httpApi:
          path: /customers/{customerId}/credits
          method: post
  updateCustomerCredit:
    handler: dist/customers/infrastructure/http/handlers/update-customer-credit.handler
    events:
      - httpApi:
          path: /customers/{customerId}/credits/{creditId}
          method: patch

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  dotenv:
    path: .env.${opt:stage, 'local'}
