service: serverless-app

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  health:
    handler: dist/core/infrastructure/http/handlers/health.handler
    events:
      - httpApi:
          path: /health
          method: get
  info:
    handler: dist/core/infrastructure/http/handlers/info.handler
    events:
      - httpApi:
          path: /info
          method: get

plugins:
  - serverless-offline
